language: python
python:
- '3.6'
cache: pip
branches:
  only:
  - master
before_install:
- sudo apt-get update
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- source "$HOME/miniconda/etc/profile.d/conda.sh"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
install:
- conda create -q -n build-environment python=$TRAVIS_PYTHON_VERSION
- conda activate build-environment
- conda install -c anaconda -c conda-forge -c plotly --yes --file requirements.txt
script:
- make publish
before_deploy:
- npm install -g netlify-cli
deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -a $NETLIFY_AUTH_TOKEN -p
  skip_cleanup: true
env:
  global:
  - secure: db0R61lGk+J5h8X4Zb2RdbvC1dWopcbbPViN8GwsTKAAD/tDSTVm9C1HKbte0YJTACGUS2N2ioGzkk7DFTnoUP58tT1jXQqQlY0QGPXQKrKcBZ9GcN8E0hSBMgsRhO7mgV0duvhoJLxNQR4tOQHVABWRyPaI+rAg1cVTpv/2+lsuF7EE9CLkJkBp8Q1JHLGbG7Q7+/neRlSykOvNof8X547vx8ljHUFlgQROWP5jjiQV+y9j/TywYsmR5LTVb53M4It9IwPS61GC27D25tYgudLZkIAe87i0L33JSukHDdpyAwMbUz/Ow5VDuBY+bhsJ9AXjoRAh68moDqIaRwELPUVvpnjmY0Qf2uJ9ncPgFDaUfRcnq6oJBwxuU1w8N25/go2McR896BrXS2q+3c9CVVbVntg/q6cXdKu1+Nylbobua88XMMt4ZzlW0vwKp3+x+YxNTWnYEW9usuSXfnPs0YQgG/ZlX7S7hRif9snYCPnex8USSF9nqNveRD6qvn11q0fS7sgf792mLtfHIQBkDLSdVdivOQaVgqCrlKvAVqHUHppMOMfuO5Y9WiSLqp3oKXCy/rMmGJLQWEZinYOcKRPOzM4zpZdwQzjv9G9kVbOuHT/W1bdCOH+VtvWd1qAeTSM6bCjHWG9A4k08b3id0ndEMd86Thd4TTS/31tt/IY=
  - secure: p8px5N3d6TF66xh+86ebspHYtNoXWniv5fMfu3LI/Yol55DB1htF0+KVgGdkQBfBJqi0ikxnGry3hB4yShCRprdFer5c4neE4GMpy6sE+NxMQiX+URvHkHlDD49YdWFeW2FHFIWvI0wslJlrdXF7rpi6TFHL3TQzLQWb1HruxgMYcjjFUrU+1QqmxmnV/9v/VYsBKmLziYaVTZMFk229m4SI985qUZ16bVy8AHsTB8VKvyXCiQTpPkIyuH7R1WNkY9jX1PE0NroGnwYMGAQX9NU9QdOQrm4WTuGpayP8Hj/wpXau7vdrCGi6YZ2wTa49r6WpyPD9zndmjh1WRBTwoVJ4F54ifE/jLCZXGvYXPgXe0HNK1LH4bXkOGyIJ96HLJazEysno18RSi/isl5diC79bTQSsudPjpX1CJ+5FfVKVicxaVf4BZu9wtCkfQfIWdJ6yz6KCt7C0v8LmsDQHQQjFmM/+6GB2eb8LY0SZt11NtWpa/5mFV3nf4bUAhU3Buclyb2MW6dTGNvy4htBq02CRnHBtdmpf/42WofHQGf0ab6F7PWFuxqUkZtHy78bzrBKfSgZIZdMZUYUBpF61rNu+FZTtJZx3yy08O96nS7lcHXH4UbryNAO14K5/u7sO1iQeV9V/9eJDCTilQDzT5/FM1sFNin2K06SROER7fjw=
