version: "3"

services:
  jupyter:
    build:
      context: .
      dockerfile: docker/jupyter/Dockerfile
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/work
