name: ci

on: push

env:
  PYTHON_VERSION: "3.10"

jobs:
  ci:
    name: Test Jupyter Notebooks

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache Conda Dependencies
        uses: actions/cache@v4
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-${{ env.PYTHON_VERSION }}-conda-${{ hashFiles('requirements.txt') }}

      - name: Install Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ env.PYTHON_VERSION }}
          channels: conda-forge,anaconda,plotly
          allow-softlinks: true
          channel-priority: flexible
          show-channel-urls: true
          use-only-tar-bz2: true
          auto-activate-base: true
          activate-environment: true

      - run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show

      # - name: Install Conda Dependencies
      #   run: conda install --yes --file requirements.txt

      # - name: Execute all Notebooks
      #   run: |
      #     conda install pytest
      #     $CONDA/bin/pytest test/

      - name: Build website
        run: |
          python -m pip install pelican
          make html
